# https://vite.dev/guide/static-deploy#github-pagess
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Adding Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/kwweld
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
